### ISSUE TITLE
Request: ogImage

### ISSUE THREAD

**Issue by iamdangavin** [robertbrodrecht/launchpad#28]
Default Opengraph image in the social area. If there isn't a post thumbnail or an image on the page, default back to this image.

[Robert adds: Also look into @adactio's merging of OG and Twitter meta tags.]

**Comment by iamdangavin** [comment]
You are referring to this, correct? Merging the `name` and `property` tags into the same `meta` markup
```
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@bigbhm">
<meta name="twitter:url" property="og:url" content="http://bigcom.com">
<meta name="twitter:title" property="og:title" content="Metadata markup">
<meta name="twitter:description" property="og:description" content="So many standards to choose from.">
<meta name="twitter:image" property="og:image" content="https://bigcom.com/icon.png">
```

**Comment by robertbrodrecht** [comment]
Yeah, something like that.  I say "something like that" because I haven't fully done the research.  If you have, then yes, that.  This is the article I was referencing, which it appears you found.  https://adactio.com/journal/9881
