### ISSUE TITLE
"of" Keyword in Columns

### ISSUE THREAD

**Issue by robertbrodrecht** [robertbrodrecht/launchpad#31]
Allow for "x of y" in columns like the new Foundation has. Allows for dynamic switching of column count.  So, I could do the following inside of a 12 column grid:

```
@include col(33 of 100)
```

**Comment by iamdangavin** [comment]
@robertbrodrecht check this out with the use of the [percentage(col/sum)](http://thesassway.com/intermediate/simple-grid-mixins#making-the-column-mixin-robust)

**Comment by robertbrodrecht** [comment]
Added.  Needs some testing.
